POST http://localhost:5001/reset-password
Content-Type: application/json

{   
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc2NjEyNTQ5NDIsImVtYWlsIjoianVsaWJhcmJlcjIyQGdtYWlsLmNvbSIsImlhdCI6MTY1NzY1NzY1NH0.zly75GPyibK8PLpzu2vS8_HUGaF2nO_m6OFjeHmXshM",
    "email": "julibarber22@gmail.com",
    "password": "asdf1234",
    "confirmPassword": "asdf1234"
}
