POST http://localhost:5001/user/create
Authorization: Bearer {{$dotenv AUTHORIZATION_TOKEN}}
Content-Type: application/json

{   
    "name": "Giulia",
    "lastname": "Barber",
    "email": "julibarber22@gmail.com",
    "password": "123123"
}
